on: [pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.5'
    - name: Setup reviewdog
      run: |
        mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
        echo ::add-path::$HOME/bin
        echo ::add-path::$(go env GOPATH)/bin # for Go projects
    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go vet ./... | reviewdog -f=govet -reporter=github-pr-review
    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}