
on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.5'
    - run: go run main.go
    - run: go test ./...
    - run: go vet ./...
    - run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
    - run: golangci-lint run ./...